import type { Proposta } from './types';

const propostas: Proposta[] = [
    {
        slug: 'llcontabilidade',
        cliente: 'L&L Contabilidade',
        servico: 'Sistema Web para Escritório de Contabilidade',
        descricao: 'Uma plataforma digital moderna que centraliza documentos, clientes e comunicação — acessível de qualquer dispositivo, a qualquer hora.',
        data: 'Março 2026',
        badgeLabel: 'Proposta Comercial · Março 2026',
        heroTitulo: 'Sistema Web para',
        heroSubtitulo: 'Escritório de\nContabilidade',
        techStack: ['⚡ Next.js', '🗄 Supabase', '🐘 PostgreSQL', '☁️ Vercel'],
        cores: {
            primaria: '#3a4e45',
            secundaria: '#be955f',
            textoPrimaria: '#ffffff',
            textoSecundaria: '#ffffff',
        },
        sistema: {
            titulo: 'Duas áreas, uma plataforma',
            subtitulo: 'O sistema funciona 100% online, direto no navegador — sem instalar nada. Acesse do computador, tablet ou celular, a qualquer hora.',
            areas: [
                {
                    icone: '👨‍💼',
                    titulo: 'Área do Contador',
                    descricao: 'Controle total da operação do escritório em um só lugar.',
                    dark: true,
                    features: [
                        'Gerenciamento de todos os clientes e empresas',
                        'Upload e organização de documentos',
                        'Dashboard com visão geral das atividades',
                        'Controle de acesso e usuários',
                        'Comunicação direta com clientes',
                        'Monitoramento e relatórios de atividades',
                    ],
                },
                {
                    icone: '🏢',
                    titulo: 'Área do Cliente',
                    descricao: 'Portal exclusivo para cada empresa atendida pelo escritório.',
                    dark: false,
                    features: [
                        'Acesso seguro com login próprio',
                        'Visualização e download de documentos',
                        'Acompanhamento de pendências',
                        'Comunicação direta com o escritório',
                        'Histórico de documentos enviados e recebidos',
                        'Interface limpa e fácil de usar',
                    ],
                },
            ],
        },
        planos: [
            {
                id: 'plano1',
                nome: 'Plano Fixo',
                subtitulo: 'Previsibilidade total — você sabe exatamente o que vai pagar todo mês.',
                badge: 'Plano 1',
                corHeader: '#1B3A6B',
                corBadge: 'rgba(74,144,217,.2)',
                corBadgeText: '#C8DEFF',
                corDestaque: '#2462C8',
                desenvolvimento: 'R$ 2.500',
                mensalidade: 'R$ 400',
                mensalidadeLabel: 'Mensalidade',
                features: [
                    { text: 'Sistema web completo' },
                    { text: 'Login e autenticação segura' },
                    { text: 'Área do contador e do cliente' },
                    { text: 'Cadastro de clientes e empresas' },
                    { text: 'Upload e organização de documentos' },
                    { text: 'Dashboard básico' },
                    { text: 'Correção de bugs e manutenção' },
                    { text: 'Pequenas melhorias contínuas' },
                    { text: 'Suporte técnico' },
                ],
            },
            {
                id: 'plano2',
                nome: 'Plano Crescimento',
                subtitulo: 'Sistema completo — você paga de acordo com o tamanho do seu escritório.',
                badge: 'Plano 2',
                featured: true,
                corHeader: '#0D6E3F',
                corBadge: 'rgba(255,255,255,.15)',
                corBadgeText: '#d1fae5',
                corDestaque: '#0D6E3F',
                desenvolvimento: 'R$ 2.000',
                mensalidade: 'R$ 50',
                mensalidadeLabel: 'Por cliente/mês',
                simulator: {
                    precoUnitario: 50,
                    min: 5,
                    max: 100,
                    label: 'Simule sua mensalidade',
                },
                nota: 'Mínimo mensal: 5 clientes = R$ 250/mês',
                features: [
                    { text: 'Sistema completo com interface avançada', bold: true },
                    { text: 'Login e autenticação segura' },
                    { text: 'Área do contador e do cliente' },
                    { text: 'Dashboard completo e detalhado', bold: true },
                    { text: 'Upload e organização de documentos' },
                    { text: 'Estrutura preparada para crescimento futuro', bold: true },
                    { text: 'Monitoramento do sistema' },
                    { text: 'Manutenção contínua e proativa' },
                    { text: 'Suporte técnico prioritário', bold: true },
                ],
            },
            {
                id: 'plano3',
                nome: 'Plano Completo',
                subtitulo: 'A solução mais robusta com mensalidade fixa e premium.',
                badge: 'Plano 3',
                corHeader: '#4C1D95',
                corBadge: 'rgba(255,255,255,.15)',
                corBadgeText: '#ede9fe',
                corDestaque: '#4C1D95',
                desenvolvimento: 'R$ 3.500',
                mensalidade: 'R$ 500',
                mensalidadeLabel: 'Mensalidade',
                features: [
                    { text: 'Sistema completo com interface avançada' },
                    { text: 'Login e autenticação segura' },
                    { text: 'Área do contador e do cliente' },
                    { text: 'Dashboard completo e detalhado' },
                    { text: 'Upload e organização de documentos' },
                    { text: 'Estrutura preparada para crescimento' },
                    { text: 'Monitoramento do sistema' },
                    { text: 'Manutenção contínua e proativa' },
                    { text: 'Suporte técnico prioritário' },
                ],
            },
        ],
        comparativo: [
            { recurso: 'Sistema web completo', planos: ['✓', '✓', '✓'] },
            { recurso: 'Login e autenticação', planos: ['✓', '✓', '✓'] },
            { recurso: 'Área do contador', planos: ['✓', '✓', '✓'] },
            { recurso: 'Área do cliente', planos: ['✓', '✓', '✓'] },
            { recurso: 'Upload de documentos', planos: ['✓', '✓', '✓'] },
            { recurso: 'Dashboard', planos: ['Básico', 'Completo', 'Completo'] },
            { recurso: 'Interface avançada', planos: ['—', '✓', '✓'] },
            { recurso: 'Escalabilidade futura', planos: ['Parcial', '✓', '✓'] },
            { recurso: 'Monitoramento do sistema', planos: ['—', '✓', '✓'] },
            { recurso: 'Suporte técnico', planos: ['✓', 'Prioritário', 'Prioritário'] },
            { recurso: 'Manutenção contínua', planos: ['✓', '✓', '✓'] },
            { recurso: 'Desenvolvimento', planos: ['R$ 2.500', 'R$ 2.000', 'R$ 3.500'] },
            { recurso: 'Mensalidade', planos: ['R$ 400 fixo', 'R$ 50/cliente', 'R$ 500 fixo'] },
        ],
        observacoes: {
            titulo: 'Observações Importantes',
            intro: 'Todas as funcionalidades descritas em cada plano já estão incluídas no escopo de desenvolvimento — nenhuma surpresa durante o projeto.',
            items: [
                'Novos módulos ou funcionalidades não previstas inicialmente',
                'Integrações com sistemas externos solicitadas após a entrega',
                'Alterações significativas no escopo original do projeto',
                'Novas telas ou fluxos completamente diferentes do acordado',
            ],
            rodape: 'Qualquer solicitação fora do escopo será previamente orçada e aprovada — sem cobranças surpresa.',
        },
        passos: [
            { numero: '01', titulo: 'Alinhamento e assinatura do contrato', descricao: 'Definimos juntos o plano escolhido e formalizamos o acordo.', cor: '#1B3A6B' },
            { numero: '02', titulo: 'Levantamento detalhado dos requisitos', descricao: 'Mapeamos todos os fluxos e necessidades específicas do escritório.', cor: '#2462C8' },
            { numero: '03', titulo: 'Desenvolvimento e entrega em etapas', descricao: 'Construímos o sistema com entregas parciais para acompanhamento.', cor: '#4A90D9' },
            { numero: '04', titulo: 'Testes e validação com sua equipe', descricao: 'Você e sua equipe testam tudo antes de publicar.', cor: '#0D6E3F' },
            { numero: '05', titulo: 'Publicação e treinamento', descricao: 'Sistema no ar e equipe treinada para usar com confiança.', cor: '#4C1D95' },
        ],
        contato: {
            email: 'tkodelabs@gmail.com',
            whatsapp: 'https://wa.me/5586988695332',
            mensagem: 'Estamos prontos para transformar o seu escritório digitalmente.\nFale conosco para tirar dúvidas ou ajustar esta proposta.',
        },
    },
];

export function getProposta(slug: string): Proposta | undefined {
    return propostas.find(p => p.slug === slug);
}

export function getAllPropostas(): Proposta[] {
    return propostas;
}
