import type { Proposta } from './types';

const propostas: Proposta[] = [
    {
        slug: 'llcontabilidade',
        cliente: 'L&L Contabilidade',
        servico: 'Sistema Web para Escritório de Contabilidade',
        descricao: 'Uma plataforma digital moderna que centraliza documentos, clientes e comunicação — acessível de qualquer dispositivo, a qualquer hora.',
        data: 'Março 2026',
        badgeLabel: 'Proposta Comercial · Março 2026',
        heroTitulo: 'Sistema Web para',
        heroSubtitulo: 'Escritório de\nContabilidade',
        techStack: ['⚡ Next.js', '🗄 Supabase', '🐘 PostgreSQL', '☁️ Vercel'],
        cores: {
            primaria: '#3a4e45',
            secundaria: '#be955f',
            textoPrimaria: '#ffffff',
            textoSecundaria: '#ffffff',
        },
        sistema: {
            titulo: 'Duas áreas, uma plataforma',
            subtitulo: 'O sistema funciona 100% online, direto no navegador — sem instalar nada. Acesse do computador, tablet ou celular, a qualquer hora.',
            areas: [
                {
                    icone: '👨‍💼',
                    titulo: 'Área do Contador',
                    descricao: 'Controle total da operação do escritório em um só lugar.',
                    dark: true,
                    features: [
                        'Gestão centralizada de clientes e empresas (GED)',
                        'Envio em massa e organização de documentos fiscais',
                        'Calendário dinâmico de vencimentos (Alertas)',
                        'Protocolos Digitais com confirmação de visualização',
                        'Controle de acesso seguro para equipe contábil',
                        'Monitoramento e relatórios de métricas do escritório',
                    ],
                },
                {
                    icone: '🏢',
                    titulo: 'Área do Cliente',
                    descricao: 'Portal exclusivo para cada empresa atendida pelo escritório.',
                    dark: false,
                    features: [
                        'Acesso web ou mobile com login criptografado próprio',
                        'Visualização fácil de guias, recibos e declarações',
                        'Módulo Simplificado de Solicitações (Chamados)',
                        'Consulta ao calendário de obrigações da empresa',
                        'Histórico auditável de documentos enviados ou recebidos',
                        'Canal integrado para não perder informações no WhatsApp',
                    ],
                },
            ],
        },
        planos: [
            {
                id: 'plano1',
                nome: 'Plano Essencial',
                subtitulo: 'Focado em organizar a casa, parar de usar WhatsApp para processos e enviar documentos com segurança.',
                badge: 'Essencial',
                corHeader: '#1B3A6B',
                corBadge: 'rgba(74,144,217,.2)',
                corBadgeText: '#C8DEFF',
                corDestaque: '#2462C8',
                desenvolvimento: 'R$ 2.500',
                mensalidade: 'R$ 400',
                mensalidadeLabel: 'Mensalidade',
                features: [
                    { text: 'Portal do Cliente & Painel do Contador', bold: true },
                    { text: 'Login e autenticação criptografada' },
                    { text: 'Gestão Centralizada de Documentos (GED)' },
                    { text: 'Protocolo Digital (Confirmação de Visualização)', bold: true },
                    { text: 'Módulo de Solicitações (Admissão, Férias)' },
                    { text: 'Dashboard de Atividades Básico' },
                    { text: 'Hospedagem em Alta Performance e Manutenção' },
                ],
            },
            {
                id: 'plano2',
                nome: 'Plano Crescimento',
                subtitulo: 'A automação perfeita. Ideal para o contador que quer escalar o escritório sem perder o controle.',
                badge: 'Mais Recomendado',
                featured: true,
                corHeader: '#0D6E3F',
                corBadge: 'rgba(255,255,255,.15)',
                corBadgeText: '#d1fae5',
                corDestaque: '#0D6E3F',
                desenvolvimento: 'R$ 2.000',
                mensalidade: 'R$ 50',
                mensalidadeLabel: 'Por cliente/mês',
                simulator: {
                    precoUnitario: 50,
                    min: 5,
                    max: 100,
                    label: 'Simule sua mensalidade',
                },
                nota: 'Mínimo mensal: 5 clientes = R$ 250/mês',
                features: [
                    { text: 'Tudo do Plano Essencial', bold: true },
                    { text: 'Calendário Fiscal Dinâmico (Alertas)' },
                    { text: 'Módulo de Atendimento (Sistema de Chamados)', bold: true },
                    { text: 'Integração de Notificações Básicas' },
                    { text: 'Relatórios de Eficiência de Clientes' },
                    { text: 'Estrutura Cloud preparada para escalabilidade' },
                    { text: 'Suporte Técnico Prioritário', bold: true },
                ],
            },
            {
                id: 'plano3',
                nome: 'Plano Tech (Completo)',
                subtitulo: 'A solução definitiva para o escritório se tornar 100% digital, com emissão de notas e consultoria VIP.',
                badge: 'Premium',
                corHeader: '#4C1D95',
                corBadge: 'rgba(255,255,255,.15)',
                corBadgeText: '#ede9fe',
                corDestaque: '#4C1D95',
                desenvolvimento: 'R$ 3.500',
                mensalidade: 'R$ 500',
                mensalidadeLabel: 'Mensalidade',
                features: [
                    { text: 'Tudo do Plano Crescimento', bold: true },
                    { text: 'Módulo de Emissão de Notas (NFS-e/NF-e)', bold: true },
                    { text: 'Análise de Indicadores de Faturamento (BI)' },
                    { text: 'Treinamento Presencial/Online para Equipe' },
                    { text: 'Suporte "VIP" direto via WhatsApp' },
                    { text: 'Backup Automático Diário e Monitoramento' },
                ],
            },
        ],
        comparativo: [
            { recurso: 'Portal do Contador e do Cliente', planos: ['✓', '✓', '✓'] },
            { recurso: 'Gestão de Documentos (GED)', planos: ['✓', '✓', '✓'] },
            { recurso: 'Protocolo Digital com Data/Hora', planos: ['✓', '✓', '✓'] },
            { recurso: 'Módulo de Solicitações Básicas', planos: ['✓', '✓', '✓'] },
            { recurso: 'Hospedagem Cloud e Manutenção', planos: ['✓', '✓', '✓'] },
            { recurso: 'Módulo de Chamados/Atendimento', planos: ['—', '✓', '✓'] },
            { recurso: 'Calendário Fiscal e Alertas', planos: ['—', '✓', '✓'] },
            { recurso: 'Emissão de Notas Integrada', planos: ['—', '—', '✓'] },
            { recurso: 'Painel BI de Indicadores', planos: ['—', '—', '✓'] },
            { recurso: 'Treinamento de Equipe', planos: ['—', '—', '✓'] },
            { recurso: 'Segurança Criptografada Avançada', planos: ['Básico', 'Completo', 'Completo'] },
            { recurso: 'Suporte Técnico', planos: ['E-mail', 'Prioritário', 'WhatsApp'] },
            { recurso: 'Desenvolvimento', planos: ['R$ 2.500', 'R$ 2.000', 'R$ 3.500'] },
            { recurso: 'Mensalidade', planos: ['R$ 400 fixo', 'R$ 50/cliente', 'R$ 500 fixo'] },
        ],
        observacoes: {
            titulo: 'Observações Importantes',
            intro: 'Todas as funcionalidades descritas em cada plano já estão incluídas no escopo de desenvolvimento — nenhuma surpresa durante o projeto.',
            items: [
                'Novos módulos ou funcionalidades não previstas inicialmente',
                'Integrações com sistemas externos solicitadas após a entrega',
                'Alterações significativas no escopo original do projeto',
                'Novas telas ou fluxos completamente diferentes do acordado',
            ],
            rodape: 'Qualquer solicitação fora do escopo será previamente orçada e aprovada — sem cobranças surpresa.',
        },
        passos: [
            { numero: '01', titulo: 'Alinhamento e assinatura do contrato', descricao: 'Definimos juntos o plano escolhido e formalizamos o acordo.', cor: '#1B3A6B' },
            { numero: '02', titulo: 'Levantamento detalhado dos requisitos', descricao: 'Mapeamos todos os fluxos e necessidades específicas do escritório.', cor: '#2462C8' },
            { numero: '03', titulo: 'Desenvolvimento e entrega em etapas', descricao: 'Construímos o sistema com entregas parciais para acompanhamento.', cor: '#4A90D9' },
            { numero: '04', titulo: 'Testes e validação com sua equipe', descricao: 'Você e sua equipe testam tudo antes de publicar.', cor: '#0D6E3F' },
            { numero: '05', titulo: 'Publicação e treinamento', descricao: 'Sistema no ar e equipe treinada para usar com confiança.', cor: '#4C1D95' },
        ],
        contato: {
            email: 'tkodelabs@gmail.com',
            whatsapp: 'https://wa.me/5586988695332',
            mensagem: 'Estamos prontos para transformar o seu escritório digitalmente.\nFale conosco para tirar dúvidas ou ajustar esta proposta.',
        },
    },
];

export function getProposta(slug: string): Proposta | undefined {
    return propostas.find(p => p.slug === slug);
}

export function getAllPropostas(): Proposta[] {
    return propostas;
}
